# post http://localhost:8000/users HTTP/1.1
# content-type: application/json

# {
#     "name": "Andy",
#     "age": 30
# }

# get http://localhost:8000/users/findname?name=KL

# get http://localhost:8000/users/3

# get http://localhost:8000/users 

# get http://localhost:8000/users/hello?name=RT&age=20

# delete http://localhost:8000/users/3
